// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnrExutbKDmCuo00InCiXmc-Bc2lw1x4Q',
    appId: '1:522216344352:web:6e1aed8e6a945140ed6545',
    messagingSenderId: '522216344352',
    projectId: 'flutter-university-app-46c18',
    authDomain: 'flutter-university-app-46c18.firebaseapp.com',
    storageBucket: 'flutter-university-app-46c18.firebasestorage.app',
    measurementId: 'G-G4RZJQXNDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7SUQCtKkjtDxOby2DAXehDtbSshvQXjg',
    appId: '1:522216344352:android:fdb54359be4ecd67ed6545',
    messagingSenderId: '522216344352',
    projectId: 'flutter-university-app-46c18',
    storageBucket: 'flutter-university-app-46c18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxqHcHSey3kvZ1TgTJoTSKdnO2nnKYA1w',
    appId: '1:522216344352:ios:82e36f7dd1f98cd8ed6545',
    messagingSenderId: '522216344352',
    projectId: 'flutter-university-app-46c18',
    storageBucket: 'flutter-university-app-46c18.firebasestorage.app',
    iosBundleId: 'com.example.cityu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxqHcHSey3kvZ1TgTJoTSKdnO2nnKYA1w',
    appId: '1:522216344352:ios:82e36f7dd1f98cd8ed6545',
    messagingSenderId: '522216344352',
    projectId: 'flutter-university-app-46c18',
    storageBucket: 'flutter-university-app-46c18.firebasestorage.app',
    iosBundleId: 'com.example.cityu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnrExutbKDmCuo00InCiXmc-Bc2lw1x4Q',
    appId: '1:522216344352:web:0fab604f4cfd885fed6545',
    messagingSenderId: '522216344352',
    projectId: 'flutter-university-app-46c18',
    authDomain: 'flutter-university-app-46c18.firebaseapp.com',
    storageBucket: 'flutter-university-app-46c18.firebasestorage.app',
    measurementId: 'G-GT3B7F58JL',
  );
}
